version: "3"
services:
  nginx:
    image: nginx:1.23.0
    restart: always
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - /srv/docker/face-restoration/logs:/var/log/nginx/
    ports:
        - 10134:80
    depends_on:
        - frontend
        - backend

  backend:
    image: rmrfred/face-restoration-backend:devel
    restart: always
    build: 
      context: backend
      dockerfile: Dockerfile
    container_name: face-restoration-backend
    environment:
      API_VERSION: 1.0.0
      API_ENV: "DEV"
      PYTHONPATH: .
    volumes:
      - ./backend/app:/app

  frontend:
    restart: on-failure
    image: rmrfred/face-restoration-frontend:devel
    stdin_open: true
    build: ./frontend
    container_name: face-restoration-frontend
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend/app:/app

  face-restoration-worker:
    image: rmrfred/face-restoration-worker:latest
    restart: always
    environment:
        MODELS_PATH: /models/
        DEVICE: ${DEVICE}
    volumes:
      - /srv/docker/face-restoration-worker/logs:/logs
